version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_local
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_local
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      #- WEBHOOK_URL=http://localhost:5678/
      # recordar revisar direccion de cuenta gratuita ngrok sigue igual!
      - WEBHOOK_URL=https://jimmy-wrath-undocked.ngrok-free.dev/
      - GENERIC_TIMEZONE=America/Argentina/Buenos_Aires
      - TZ=America/Argentina/Buenos_Aires
      # VARIABLES CRÍTICAS DE SEGURIDAD PARA PASAR EL ERROR DE ACCESO:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_RESTRICT_FILE_ACCESS_TO=/files;/home/node/.n8n-files
    volumes:
      - n8n_data:/home/node/.n8n
      # Mapeo de tu carpeta física de Linux Mint al contenedor:
      - /home/dell/Documentos:/files/Documentos
    depends_on:
      - ollama
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_local
    restart: unless-stopped
    command:
      - "http"
      - "n8n:5678"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - n8n

volumes:
  n8n_data:
  ollama_data:
